// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8C6bwMBh32ecIcUYN4ox4csR8rZKSZF4',
    appId: '1:558768290000:web:f604e857ff3b420e34c6d5',
    messagingSenderId: '558768290000',
    projectId: 'voluntariapp-a9a7b',
    authDomain: 'voluntariapp-a9a7b.firebaseapp.com',
    storageBucket: 'voluntariapp-a9a7b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF5X0be8ddH4Ik8rd5HN7C-bpEdBARjd0',
    appId: '1:558768290000:android:d17b1e0d0468e36234c6d5',
    messagingSenderId: '558768290000',
    projectId: 'voluntariapp-a9a7b',
    storageBucket: 'voluntariapp-a9a7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9gePH9ppIl5ZJHNLhkJGWv2hbO6vk_c4',
    appId: '1:558768290000:ios:40637b674ceff4ca34c6d5',
    messagingSenderId: '558768290000',
    projectId: 'voluntariapp-a9a7b',
    storageBucket: 'voluntariapp-a9a7b.firebasestorage.app',
    iosBundleId: 'com.example.voluntariapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9gePH9ppIl5ZJHNLhkJGWv2hbO6vk_c4',
    appId: '1:558768290000:ios:40637b674ceff4ca34c6d5',
    messagingSenderId: '558768290000',
    projectId: 'voluntariapp-a9a7b',
    storageBucket: 'voluntariapp-a9a7b.firebasestorage.app',
    iosBundleId: 'com.example.voluntariapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8C6bwMBh32ecIcUYN4ox4csR8rZKSZF4',
    appId: '1:558768290000:web:636357acdceb8ee634c6d5',
    messagingSenderId: '558768290000',
    projectId: 'voluntariapp-a9a7b',
    authDomain: 'voluntariapp-a9a7b.firebaseapp.com',
    storageBucket: 'voluntariapp-a9a7b.firebasestorage.app',
  );
}
